#!/bin/bash
set -eo pipefail
export ETCD=$CONFD_ETCD_NODE

echo "[nginx] booting container. ETCD: $ETCD"

# Loop until confd has updated the nginx config
until confd -onetime -node $ETCD; do
  echo "[nginx] waiting for confd to refresh nginx.conf"
  sleep 5
done

# Start nginx
echo "[nginx] starting nginx service..."
service nginx start

# Run confd in the background to watch the upstream servers
echo "[confd] listen for changes on etcd..."
confd -watch -interval=10 -node $ETCD
